Last few tweaks for the logger package before it moves to CRAN
PecanProject/pecan pull request #2826
Opened 2021-07-22 16:00 UTC by moki1202

2021-07-22 17:18 UTC, mdietze approved these changes

2021-07-22 20:56 UTC, infotroph requested changes

2021-07-22 20:56 UTC, infotroph commented on base/logger/DESCRIPTION
> +    console or both.
```suggestion
Description: Convenience functions for logging outputs from 'PEcAn',
   the Predictive Ecosystem Analyzer (LeBauer et al. 2017;
   doi:10.1890/12-0137.1). Enables the user to set what level of messages are
   printed, as well as whether these messages are written to the console, 
   a file, or both. It also allows control over whether severe errors should
   stop execution of the PEcAn workflow; this allows strictness when deugging
   and lenience when running large batches of simulations that should not be
   terminated by errors in individual models. PEcAn.logger is loosely based on
   the 'log4j' package.
```

2021-07-26 12:09 UTC, infotroph commented
@moki1202 I believe the last step needed here is to bump the version (to 1.8.0, in both DESCRIPTION and NEWS.md) and date. Then we can build, final-test, and submit!

2021-07-26 21:06 UTC, infotroph commented on base/logger/DESCRIPTION
> +Date: 2019-27-07
```suggestion
Date: 2021-07-27
```

2021-07-27 06:51 UTC, infotroph approved these changes

2021-07-27 13:52 UTC, robkooper approved these changes

2021-07-27 13:52 UTC, robkooper commented
@moki1202 if you feel it is ready, mark it ready for review so it can be merged. And we can push it to cran.

2021-07-27 15:09 UTC, moki1202 commented
I believe we are ready to role!!

2021-07-27 20:30 UTC, merged