change license to BSD-3
PecanProject/pecan pull request #2896
Opened 2021-11-16 15:30 UTC by robkooper

This changes the license for PEcAn.logger to be BSD-3 from NCSA

## Description

This is a license change to make it easier to push the package to CRAN. This has been approved by:

- Alexey Shiklomanov
- Chris Black
- Michael Dietze
- Rob Kooper
- Shashank Singh
- Tony Gardella

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] My name is in the list of .zenodo.json
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-11-16 15:41 UTC, mdietze approved these changes

2021-11-16 15:50 UTC, infotroph requested changes
* Can you also update base/logger/NEWS.md and bump the package version, please? 
* I believe CRAN will ask us to remove the LICENSE file: Writing R Extensions [says](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Licensing) "The optional file LICENSE/LICENCE contains a copy of the license of the package. To avoid any confusion only include such a file if it is referred to in the ‘License’ field of the DESCRIPTION file." I believe part of their rationale is that R provides its own copies of all the standard licenses, so there's no need to install more copies of them in every package. To comply with CRAN policy while keeping the license available in non-CRAN distributions, we could either
    - keep LICENSE in every package but add it to .Rbuildignore, or
    - keep one copy of LICENSE at the top level of the repository and delete it from individual packages.

2021-12-02 09:52 UTC, infotroph commented on base/logger/NEWS.md
> +## PEcAn.logger 1.7.1
```suggestion
# PEcAn.logger 1.7.1
```

2022-03-03 23:25 UTC, infotroph approved these changes

2022-03-05 21:35 UTC, merged