Adding soil moisture IC function
PecanProject/pecan pull request #2905
Opened 2022-01-19 18:19 UTC by helge22a

## Description

The SIPNET model has the ability to run with soil moisture initial condition, so this function will download the latest vswc from EFI and create a netcdf. 
## Motivation and Context

Want to be able to run SIPNET with soil moisture IC.
## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] My name is in the list of .zenodo.json
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-24 19:03 UTC, mdietze requested changes

2022-03-24 19:03 UTC, mdietze commented on modules/data.land/R/cohort2pool.R
> +  outdir = "/projectnb/dietzelab/ahelgeso/NEON_ic_data/Harvard/neon_nc_ens/"
Site and outdir shouldn't be hard coded. More generally, these changes seem like they should have been in a different PR

2022-03-24 19:03 UTC, mdietze commented on modules/data.land/R/download_vswc.R
> +download_vswc <- function(outdir, site_ID) {
feel like the name should be more specific since this only get soil moisture from one source (NEON data as processed by EFI challenge)

2022-10-28 14:46 UTC, helge22a commented
This PR will close #2833

2022-10-28 14:50 UTC, helge22a commented
This PR is superseded by PR #3036

2022-10-28 14:50 UTC, closed without merging