Var to nc var (replaces #2791)
PecanProject/pecan pull request #2918
Opened 2022-03-25 10:07 UTC by infotroph

Incorporates @moki1202's work from #2791, which is ready to merge but would be a pain to do because the upstream branch is gone. Opening this PR as the easiest way forward.

## Description

## Motivation and Context

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] My name is in the list of .zenodo.json
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2022-03-25 11:08 UTC, mdietze requested changes

2022-03-25 11:08 UTC, mdietze commented on models/gday/R/model2netcdf.GDAY.R
> +    #nc_var[[13]]  <- PEcAn.utils::to_ncvar("SoilC", "kgC/m2", list(lon,lat,t), -999)
If you change the name of this list from var to nc_var, you also need to change where the list is used in the nc_create, for, and ncvar_put below.

2022-03-25 11:08 UTC, mdietze commented on models/linkages/R/model2netcdf.LINKAGES.R
> +    nc_var[[16]] <- ncdf4::ncvar_def("PFT", units = "", dim = list(dim.pfts),
same point about changing list name

2022-03-25 11:08 UTC, mdietze commented on models/lpjguess/R/model2netcdf.LPJGUESS.R
> +      ncdf4::ncvar_put(nc, nc_var[[i]], output[[i]])
also need to change the nc_create and for above

2022-03-25 11:08 UTC, mdietze commented on models/maespa/R/model2netcdf.MAESPA.R
> +      ncdf4::ncvar_put(nc, nc_var[[i]], output[[i]])
nc_create and for

2022-03-25 11:08 UTC, mdietze commented on models/preles/R/runPRELES.jobsh.R
> +      ncdf4::ncvar_put(nc, nc_var[[i]], output[[i]])
nc_create and for

2022-03-30 05:34 UTC, moki1202 commented
@mdietze will be looking at the suggested changes ASAP!

2022-05-18 19:28 UTC, mdietze approved these changes

2022-05-18 19:28 UTC, merged