Fixed Documentation warnings from PEcAn.emulator
PecanProject/pecan pull request #2983
Opened 2022-07-24 16:53 UTC by nanu1605

2022-07-25 07:30 UTC, moki1202 commented
@nanu1605 just mentioning here the arguments that still need to be documented-

- [ ] myY
- [ ] maxval
- [ ] ic
- [ ] rate
- [ ] xnew
- [ ] pos.check
- [ ] SSnew
- [ ] ycurr
- [ ] ynew

2022-07-25 11:47 UTC, nanu1605 commented
I was searching for their description but wasn't able to find them. I was about to ask in the #cran channel regarding their description.

2022-07-28 06:49 UTC, infotroph commented on modules/emulator/R/ldinvgamma.R
> +##' @param scale scale, NULL by default
A lot of the functions in this package that take `x` arguments aren't plotting anything, but rather computing densities of statistical distributions, so "name of variable to plot" isn't the right description. What to replace it with will differ from one function to another; here's a suggestion for this one, but please check the others too.

```suggestion
##' @param x vector of quantiles
##' @param shape,scale shape and scale parameters for the inverse Gamma distribution
```

2022-07-29 08:04 UTC, nanu1605 commented
@infotroph @moki1202 Is something missing in `data.land`? the CI checks are failing because of it

2022-08-01 05:54 UTC, moki1202 commented
@nanu1605 I don't think `data.land` would cause any `CI check` failure atleast in this PR. Maybe I missed something. Can you mention the lines you're referring to?

2022-08-29 20:17 UTC, mdietze requested changes

2022-08-29 20:17 UTC, mdietze commented on modules/emulator/R/GaussProcess.R
> +##' @param y Name of variable to plot on Y axis
I don't think this function plots anything. Y is our dependent variable (I assume a vector) and X is our set of independent variables (I assume a matrix?)

2022-08-29 20:17 UTC, mdietze commented on modules/emulator/R/calcSpatialCov.R
> +##' @param ... Adiitional arguments
additional is spelled wrong

2022-08-29 20:17 UTC, mdietze commented on modules/emulator/R/calcSpatialCov.R
> +##' @param x Name of variable to plot on X axis
Likewise, X here isn't a plot. If you look at the two options that get called (calcSpatialCov.list and calcSpatialCov.matrix) the first argument is either a spatial distance matrix or a list of component spatial distance matrices

2022-08-29 20:17 UTC, mdietze commented on modules/emulator/R/distance.R
> +##' @param x Name of variable to plot on X axis
X here is a matrix of locations in physical or parameter space

2022-08-29 20:17 UTC, mdietze commented on modules/emulator/R/distance.matrix.R
> +##' @param x Name of variable to plot on X axis
X here is also a matrix of locations in parameter space

2022-08-29 20:17 UTC, mdietze commented on modules/emulator/R/distance12.matrix.R
> +##' @param x Name of variable to plot on X axis
matrix of locations in parameter space

2022-08-29 20:17 UTC, mdietze commented on modules/emulator/R/groupid.R
> +##' @param x Name of variable to plot on X axis
matrix of parameter values

2022-08-29 20:17 UTC, mdietze commented on modules/emulator/R/minimize.GP.R
> +##' @param x Name of variable to plot on X axis
vector of values (e.g. observations) to be evaluated by the specified probability density function

2022-08-29 20:17 UTC, mdietze commented on modules/emulator/R/minimize.GP.R
> +##' @param prior 'unif', 'IG'
data.frame specifying a prior probability distribution in terms of the distribution name (distn) and first and second parameters (parama, paramb)

2022-08-29 20:17 UTC, mdietze commented on modules/emulator/R/p.R
> +##' @param x Name of variable to plot on X axis
jump distribution

2022-09-02 18:44 UTC, mdietze approved these changes

2022-09-02 18:44 UTC, merged