Allow `ud_convert()` to work with class "difftime" (fix for #3012)
PecanProject/pecan pull request #3168
Opened 2023-05-16 19:36 UTC by Aariq

## Description

Fixes #3012 .  Checks if argument `x` is difftime, and if it is converts it to a `units` object with `as_units()`.  Units are inferred from the class, so argument `u1` isn't actually used in the conversion in this case.  UI is a little weird here, but seems like this is mostly an internal function so probably better than adding argument defaults and allowing `u1` to be `NULL` or something like that.

## Motivation and Context

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [ ] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] My name is in the list of CITATION.cff
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-05-17 04:34 UTC, dlebauer requested changes
Looks great- just make sure to update the change log!

2023-05-17 05:16 UTC, infotroph commented on base/utils/R/ud_convert.R
> +    x1 <- units::as_units(x)
I'm nervous about ignoring `u1` here -- I don't know how often units(x) and u1 will mismatch in practice, but when they do it means at a minimum that the user's expectations are wrong and the earlier we alert them the better.

Maybe something like...?
```suggestion
    stopifnot(units::as_units(units(x)) == units::as_units(u1))
    x1 <- units::as_units(x)
```

2023-05-17 16:26 UTC, Aariq commented
> Looks great- just make sure to update the change log!

I can do this, but I'll just point out that the changelog already includes a bullet about this function being re-factored for this version.  This bug was an unforseen side-effect of that refactoring

2023-05-17 20:06 UTC, infotroph approved these changes

2023-06-08 15:12 UTC, dlebauer approved these changes

2023-06-08 16:09 UTC, merged