build: Remove repeated steps for develop branch in workflow
PecanProject/pecan pull request #3216
Opened 2023-09-09 16:26 UTC by RohanSasne

## Description

This PR resolved #3187

I was proposing that we skip the [Renderbook](https://github.com/PecanProject/pecan/blob/d52d0d678246e8d59ba1b3eabb397ccbac0cbb72/.github/workflows/book.yml#L3-L7) and [CI](https://github.com/PecanProject/pecan/blob/d52d0d678246e8d59ba1b3eabb397ccbac0cbb72/.github/workflows/ci.yml#L3-L7) tests on it's merge with the develop branch as the tests would already have been passed in the merge group.

No need to update the Docker workflow as it will publish the latest images on DockerHub once we merge the PR onto the develop branch.

But the workflow for CI and Renderbook might be skipped as for CI we do not publish it anywhere and for Renderbook, it gets published to github in the merge queue itself [(Example)](https://github.com/PecanProject/pecan/actions/runs/5212813931).
## Motivation and Context

Currently the workflow goes like, on approval of a PR, we go on to put the PR in the merge group where workflow will get triggered and then when the PR will get merged, a second workflow will get triggered on merger into the develop branch.

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] My name is in the list of CITATION.cff
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-11-25 23:13 UTC, infotroph requested changes
Thanks for your patience on this, @RohanSasne -- I should have looked at this a long time ago.

> I was proposing that we skip the [Renderbook](https://github.com/PecanProject/pecan/blob/d52d0d678246e8d59ba1b3eabb397ccbac0cbb72/.github/workflows/book.yml#L3-L7) and [CI](https://github.com/PecanProject/pecan/blob/d52d0d678246e8d59ba1b3eabb397ccbac0cbb72/.github/workflows/ci.yml#L3-L7) tests on it's merge with the develop branch as the tests would already have been passed in the merge group.

The catch here is that the renderbook job does _run_ on all PRs, but it only _deploys_ from master and develop* -- note the `if: github.event_name != 'pull_request'` on lines 55 and  63 of book.yml. So as written this would make us only update the documentation when we push to master for official releases. We could certainly change the deployment rule to make the deployment happen in the merge group if we wanted, but we'd need another way to avoid deploying documentation changes from PRs that aren't merged.

*(Technically it only deploys from "anything that's not a PR", but we should change that -- see #3152)

I'm also cautious about skipping the CI job after merge -- yes, it's theoretically a duplicate of the tests in the merge group, but it does on occasion (once a year or so, maybe?) catch failures that didn't show up in the PR for one reason or another. I'll defer to @robkooper on whether those catches have been worth the daily extra CI runtime.

2023-11-28 18:17 UTC, RohanSasne commented
> I'm also cautious about skipping the CI job after merge -- yes, it's theoretically a duplicate of the tests in the merge group, but it does on occasion (once a year or so, maybe?) catch failures that didn't show up in the PR for one reason or another. I'll defer to @robkooper on whether those catches have been worth the daily extra CI runtime.

Yes sure, will update the PR when the review is completed :)

2024-05-16 18:05 UTC, mdietze commented
@GandalfGwaihir @infotroph wanted to check in on the status of this PR and the requested changes. Is this something that can be wrapped up soon?

2024-05-17 05:45 UTC, infotroph commented
@mdietze @GandalfGwaihir From my perspective this is waiting for changes that address my concerns above, particularly  about book.yml -- I'm confident that this were if merged as-is we'd break book deployment.

2025-08-16 00:12 UTC, infotroph commented
@allgandalf I'm going to close this since the relevant files have changed a lot and I think all the runs discussed here actually are needed -- happy to chat more / review a fresh patch if you're still seeing an issue.

2025-08-16 00:12 UTC, closed without merging