fix check warnings/notes in benchmark package
PecanProject/pecan pull request #3217
Opened 2023-09-14 01:40 UTC by moki1202

2024-01-11 08:39 UTC, infotroph commented on modules/benchmark/R/align_data.R
> +  model.calc$round.posix <- as.POSIXct(round(model.calc$posix), units = coarse.unit)
This is a tricky one, but I think `units` was correctly inside the `round` call here -- the calculation will dispatch to `round.POSIXt`, which accepts a `units` argument even though none is documented for the `round` generic. 
```suggestion
  obvs.calc$round.posix  <- as.POSIXct(round(obvs.calc$posix,  units = coarse.unit))
  model.calc$round.posix <- as.POSIXct(round(model.calc$posix, units = coarse.unit))
```

2024-01-11 08:39 UTC, infotroph commented on modules/benchmark/R/metric_residual_plot.R
> +  p <- p + ggplot2::geom_point(ggplot2::aes(y = diff), size = 4, colour = "#619CFF")
```suggestion
    p <- ggplot2::ggplot(data = metric_dat, ggplot2::aes(x = .data$time)) 
  p <- p + ggplot2::geom_path(ggplot2::aes(y = .data$zeros), colour = "#666666", size = 2, linetype = 2, lineend = "round") 
  p <- p + ggplot2::geom_point(ggplot2::aes(y = .data$diff), size = 4, colour = "#619CFF") 
```

2024-01-11 08:39 UTC, infotroph commented on modules/benchmark/R/metric_timeseries_plot.R
> +  p <- ggplot(data = metric_dat, ggplot2::aes(x = metric_dat$time))
```suggestion
  p <- ggplot(data = metric_dat, ggplot2::aes(x = .data$time)) 
```

2024-02-13 21:42 UTC, infotroph requested changes

2024-02-13 21:42 UTC, infotroph commented on modules/benchmark/R/metric_lmDiag_plot.R
> +  p1 <- ggplot2::ggplot(fit, ggplot2::aes(.fitted, .resid))
```suggestion
  p1 <- ggplot2::ggplot(fit, ggplot2::aes(.data$.fitted, .data$.resid))
```
Here's another sneaky one: Where did `.fitted` and `.resid` come from and how do we keep R CMD check from complaining about them? Well! 
<img width="925" alt="Screenshot 2024-02-13 at 1 34 06 PM" src="https://github.com/PecanProject/pecan/assets/1256435/63d71929-455b-40c7-a99e-dd579861a8ca">
It turns out ggplot is converting the `fit` object into a data frame under the hood using `fortify()`, so we can pass any of the names `fortify.lm` creates into `.data` just as if they were already present in the dataframe.
<img width="643" alt="Screenshot 2024-02-13 at 1 35 10 PM" src="https://github.com/PecanProject/pecan/assets/1256435/6c9a0a29-5bef-478e-a217-234fe1571146">

2024-02-13 21:42 UTC, infotroph commented on modules/benchmark/R/metric_lmDiag_plot.R
> +  p1 <- ggplot2::ggplot(fit, ggplot2::aes(.fitted, .resid))
(This feels like a lot of magic to rely on here, but when trying to make the package checks quiet down I think simply prefixing `.data$` on what's already here is the right call)

2024-02-13 21:42 UTC, infotroph commented on modules/benchmark/R/metric_lmDiag_plot.R
> +  p2 <- ggplot2::ggplot(fit, ggplot2::aes(stats::qqnorm(.stdresid)[[1]], .stdresid))
```suggestion
  p2 <- ggplot2::ggplot(fit, ggplot2::aes(stats::qqnorm(.data$.stdresid)[[1]], .data$.stdresid)) 
```

2024-02-13 21:42 UTC, infotroph commented on modules/benchmark/R/metric_lmDiag_plot.R
> +  p2 <- p2 + ggplot2::geom_abline(ggplot2::aes(stats::qqline(.stdresid)))
```suggestion
  p2 <- p2 + ggplot2::geom_abline(ggplot2::aes(stats::qqline(.data$.stdresid))) 
```

2024-02-13 21:42 UTC, infotroph commented on modules/benchmark/R/metric_lmDiag_plot.R
> +  p3 <- ggplot2::ggplot(fit, ggplot2::aes(.fitted, sqrt(abs(.stdresid))))
```suggestion
  p3 <- ggplot2::ggplot(fit, ggplot2::aes(.fitted, sqrt(abs(.data$.stdresid)))) 
```

2024-02-13 21:42 UTC, infotroph commented on modules/benchmark/R/metric_lmDiag_plot.R
> +  p4 <- ggplot2:: ggplot(fit, ggplot2::aes(seq_along(.cooksd), .cooksd))
```suggestion
  p4 <- ggplot2:: ggplot(fit, ggplot2::aes(seq_along(.data$.cooksd), .data$.cooksd)) 
```

2024-02-13 21:42 UTC, infotroph commented on modules/benchmark/R/metric_lmDiag_plot.R
> +  p5 <- p5 + ggplot2::geom_point(ggplot2::aes(size = .cooksd), na.rm = TRUE)
```suggestion
  p5 <- ggplot2::ggplot(fit, ggplot2::aes(.data$.hat, .data$.stdresid)) 
  p5 <- p5 + ggplot2::geom_point(ggplot2::aes(size = .data$.cooksd), na.rm = TRUE)
```

2024-02-13 21:42 UTC, infotroph commented on modules/benchmark/R/metric_lmDiag_plot.R
> +  p6 <- ggplot2::ggplot(fit, ggplot2::aes(.hat, .cooksd))
```suggestion
  p6 <- ggplot2::ggplot(fit, ggplot2::aes(.data$.hat, .data$.cooksd)) 
```

2024-02-13 21:42 UTC, infotroph commented on modules/benchmark/R/metric_scatter_plot.R
> +  p <- p + ggplot2::geom_point(ggplot2::aes(x = model, y = obvs), size = 4)
```suggestion
  p <- p + ggplot2::geom_point(ggplot2::aes(x = .data$model, y = .data$obvs), size = 4) 
```

2024-02-13 21:42 UTC, infotroph commented on modules/benchmark/R/metric_timeseries_plot.R
> +  p <- p + geom_point(ggplot2::aes(y = obvs, colour = "Observed"), size = 4)
```suggestion
  p <- p + geom_path(ggplot2::aes(y = .data$model, colour = "Model"), size = 2) 
  p <- p + geom_point(ggplot2::aes(y = .data$model, colour = "Model"), size = 4) 
  p <- p + geom_path(ggplot2::aes(y = .data$obvs, colour = "Observed"), size = 2) 
  p <- p + geom_point(ggplot2::aes(y = .data$obvs, colour = "Observed"), size = 4)
```

2024-03-02 05:58 UTC, infotroph commented on modules/benchmark/R/metric_residual_plot.R
> +    p <- ggplot2::ggplot(data = metric_dat, ggplot2::aes(x = .data$time))
```suggestion
  p <- ggplot2::ggplot(data = metric_dat, ggplot2::aes(x = .data$time)) 
```

2024-03-03 09:05 UTC, infotroph approved these changes

2024-03-04 11:02 UTC, mdietze approved these changes

2024-03-04 11:21 UTC, merged