Update write.configs.FATES.R
PecanProject/pecan pull request #3360
Opened 2024-08-19 20:03 UTC by Hhh-hyc

## Description

To update write.configs file in fates model, the goal is divided into three stages:
1. update machine configuration file to successfully generate template.job
2. update domain, surface and datm files
3. update parameters
## Motivation and Context

The first PR aims to generate basic template.job to run fates model in pecan workflow. However, the web interface of Bety doesn't work on the local machine. Thus, address of local dataset was used.

## Review Time Estimate

- [ ] Immediately
- [ ] Within one week
- [x] When possible

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue) 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] My name is in the list of CITATION.cff
- [ ] I have updated the CHANGELOG.md.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-08-19 20:50 UTC, mdietze requested changes
There's a lot that confuses me in this PR. First, it looks like this code is behind the mainline as it's deleted a lot of other people's changes. Second, it's deleted a ton of the FATES coupler without a clear substitution of an alternative structure for solving the same problem.

2024-08-19 20:50 UTC, mdietze commented on CITATION.cff
> -  - given-names: Harunobu Ishii
Unclear why you need to remove someone else's contribution

2024-08-19 20:50 UTC, mdietze commented on docker-compose.dev.yml
> +version: '3.2'
does this PR really need to touch docker files?

2024-08-19 20:50 UTC, mdietze commented on models/fates/R/write.configs.FATES.R
> +run.id <- 'test_oneyear'
Was this supposed to be an example? You can't have code like this that's outside of function.

2024-08-19 20:50 UTC, mdietze commented on models/fates/R/write.configs.FATES.R
> +   site.id <- site$id # change1: 772 -> SOD1
not following the logic of the change here. Comment is also unclear to a general user

2024-08-19 20:50 UTC, mdietze commented on models/fates/R/write.configs.FATES.R
> +   site_name    <- paste0(site.id, "_c", run.id) ## change3
I'm a bit concerned about the logic change here and on the casedir line. Could you explain what you're intending? Be aware that changes of internal logic can't change the nature of what PEcAn is passing into each function.

2024-08-19 20:50 UTC, mdietze commented on models/fates/R/write.configs.FATES.R
> +  # }
For all these large chunks of code that you've commented out, are these things that are no longer used by CLM-FATES?

2024-08-19 20:50 UTC, mdietze commented on models/fates/R/write.configs.FATES.R
> +       #var <- names(pft)[v]
Similar to previous comment, what's the reason for commenting out the last ~50 lines?

2024-08-19 20:50 UTC, mdietze commented on models/fates/R/write.configs.FATES.R
> -       }
have all of these variable names changed or are you pursuing a conceptually different approach for mapping PEcAn/BETY parameters to fates parameters?

2024-08-19 20:50 UTC, mdietze commented on models/fates/R/write.configs.FATES.R
> +   #ncdf4::nc_close(fates.param.nc)
got to the end of this and do see where a new alternative way of parameter mapping ended up being implemented

2024-08-19 20:50 UTC, mdietze commented on modules/assim.sequential/DESCRIPTION
> -    exactextractr,
Why does this PR require changes to assim.sequential?

2024-08-20 11:21 UTC, Hhh-hyc commented
Thanks for your detailed comment! @mdietze 

This PR is to show the steps in updating write.config file, and currently it's on the first stage to run the basic workflow of fates, where many fates coupler is uncommented for clarity and would be completely updated in the end. One problem is since my docker got stuck to open BETY webpage, temporarily some local address is used and name in the script is changed to run the fates model, just as you mentioned in the above comments. I would be grateful if you could have any idea in helping me solve the issue related to BETY.

As for the deleted contributions, I'm also confused cause I pushed my changes after having pulled the develop branch from upstream pecan. But I will check the version of my repository, and see if there are some problems to be solved.

2024-09-06 11:52 UTC, closed without merging